# Maximum and default receive-buffer sizes for network sockets.
# 128 MiB
net.core.rmem_max=134217728
# 16 MiB
net.core.rmem_default=16777216

# Keep incomplete IPv4 fragments for 3 seconds.
net.ipv4.ipfrag_time=3
# Maximum memory used for queued IPv4 fragments: 128 MiB.
net.ipv4.ipfrag_high_thresh=134217728
